version: "3"

services:
  # Oracle Rate Updater service container definition
  rate-oracle-service:
    image: rate-oracle-service:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: 'verbose'
    env_file:
      - .env-rate-oracle-service
    ports:
      - 3030:3030
    expose:
      - 3030
    networks:
      - rate-oracle-service

networks:
  rate-oracle-service:
    driver: bridge
